### ISSUE TITLE
Is it still alpha? And not on pypi?

### ISSUE THREAD

**Issue by guettli** [jldiaz/mkdocs-plugin-tags#11]
The README sound good. That's what I was looking for.

Is the software still alpha? It would be nice to have it on pypi.

**Comment by jldiaz** [comment]
Yes, it is still in alpha because it is fundementally for my own use. `mkdocs-material` has included a better support for tags in recent releases.

**Comment by guettli** [comment]
Thank you for the info. I will use mkdocs-material.
